site_name: Diffusion Design Works
site_url: https://crimsonvelka.github.io/DiffusionDesignWorks
theme:
  name: material
  custom_dir: overrides
  #favicon: images/favicon.png
  #icon
    #logo:
  
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs    
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  language: en

  plugins:
    - typeset
    - search
    - tags
    - glightbox
    - blog:
        post_dir: "{blog}/posts"
    - mkdocs-video
 
  markdown_extensions:
    - abbr
    - admonition
    - pymxdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    -  toc:
        permalink: true

  extra_css:
    - stylesheets/extra.css

  extra:
    generator: true
    #social:
      #- icon: fontawesome/brands/twitter
      #- link: https//twitter.com/CrimsonVelka:

  palette:

    #Toggle Dark Theme
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: deep orange
    
    #Toggle Light Theme
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: pink  

nav:
  - Home: index.md
  - About:
      - 'Introduction': About.md
  - Unlimited Diffusion Works:
      - 'Overview': pages/udw/udwmodel.md
      - 'Status Updates': pages/udw/todolist.md
      - 'Pipeline': pages/udw/udwpipeline.md
      - 'Post Processing': pages/udw/datasetpostprocess.md
      - 'Troubleshooting Flaws': pages/udw/flaws.md 
  - Motion Model Diffusion:
      - 'AnimateDiff + UDW': pages/motion/motiondiffusion.md
  #- Closing:
      - 'Lessons Learned': pages/faq/lessonslearned.md
  #- Blog:
      #- blog/index.md    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/CrimsonVelka"  target="_blank" rel="noopener">Diffusion Design Works</a>