site_name: Diffusion Design Works
site_url: https://crimsonvelka.github.io/DiffusionDesignWorks
theme:
  name: material
  custom_dir: overrides
  #favicon: images/favicon.png
  #icon
    #logo:
  
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs    
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  language: en

  plugins:
    - typeset
    - search
    - blog:
      enabled: false
      blog_toc: true

  markdown_extensions:
    - admonition
    - pymxdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    -  toc:
        permalink: true

  extra_css:
    - stylesheets/extra.css

  extra:
    generator: true
    #social:
      #- icon: fontawesome/brands/twitter
      #- link: https//twitter.com/CrimsonVelka:

  palette:

    #Toggle Light Theme
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: blue 
    
    #Toggle Dark Theme
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: blue

nav:
  - Home: index.md
  - About:
      - 'Introduction': home/About.md
  #- News:
      #- blog/posts/index.md
  - Unlimited Diffusion Works:
      - 'Overview': udw/udwmodel.md
      - 'Status Updates': udw/todolist.md
      - 'Pipeline': udw/udwpipeline.md
      - 'Post Processing': udw/datasetpostprocess.md
      - 'Troubleshooting Flaws': udw/flaws.md 
  - Motion Model Diffusion:
      - 'AnimateDiff + UDW': motion/motiondiffusion.md
  #- Closing:
      - 'Lessons Learned': faq/lessonslearned.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/CrimsonVelka"  target="_blank" rel="noopener">Diffusion Design Works</a>